### ISSUE TITLE
Vorschlagsfunktion

### ISSUE THREAD

**Issue by FunThomas424242** [FunThomas424242/rezept-dsl#6]
Die Vorschlagsfunktion ist absolut mies. Die Vorschläge orientieren sich nicht am aktuellen Kontext und stehen in keine sinnvollen Reihenfolge. 
Ich weiß diese Probleme treten erst auf seit irgendwas in EMFText verändert wurde, dennoch sollte das verbessert werden. 
Evtl. sollte ja mal über eine xtext Umsetzung nachgedacht und die Vision EMFText über Bord geworfen werden - zumal auf dem EMFText Projekt auch immer weniger passiert.

**Comment by Huluvu424242** [comment]
fixed in https://github.com/FunThomas424242/rezept-dsl.xtext
