### ISSUE TITLE
Mengenangaben

### ISSUE THREAD

**Issue by FunThomas424242** [FunThomas424242/rezept-dsl#8]
Die Mengenangaben sind wirklich nicht schön:
Zutat: "Kartoffel" Menge: "10" "Stück".
Zukünftig sollte eine Lösung gefunden werden welche ohne Anführungsstriche auskommt. Klar ist es für den Parser einfacher aber der Mensch möchte Enumerations und normale Zahlen nutzen.

**Comment by Huluvu424242** [comment]
fixed in https://github.com/FunThomas424242/rezept-dsl.xtext
